# **Projeto: Previsão de Intenção de Compra de Clientes em Loja Web**

**Descrição do Projeto**

Neste projeto, nosso objetivo é criar um sistema inteligente para antecipar a intenção de compra dos clientes em um site de e-commerce. Imagine poder prever quais clientes têm maior probabilidade de realizar compras online, com base em suas características e comportamentos passados. Essa capacidade de prever a intenção de compra não só aprimorará a experiência do cliente, mas também permitirá que a empresa direcione seus esforços de marketing de forma mais eficaz.

**Objetivo**

Queremos desenvolver um modelo preditivo capaz de analisar os padrões de comportamento dos clientes e identificar sinais que indicam a propensão deles para realizar compras no site da empresa. Para isso, vamos usar uma base de dados que contém informações detalhadas sobre os clientes, incluindo:

Dados demográficos (idade, renda, etc.)

Informações sobre compras anteriores

# Base de dados:

Year_Birth: Ano de nascimento do cliente.

Education: Nível de escolaridade do cliente.

Marital_Status: Estado civil do cliente.

Income: Renda anual da família do cliente.

Kidhome: Número de crianças na casa do cliente.

Recency: Número de dias desde a última compra do cliente.

Complain: 1 se o cliente reclamou nos últimos 2 anos, 0 caso contrário.

MntWines: Valor gasto em vinhos nos últimos 2 anos.

MntFruits: Valor gasto em frutas nos últimos 2 anos.

MntMeatProducts: Valor gasto em carnes nos últimos 2 anos.

MntFishProducts: Valor gasto em peixes nos últimos 2 anos.

MntSweetProducts: Valor gasto em doces nos últimos 2 anos.

MntGoldProds: Valor gasto em produtos de ouro nos últimos 2 anos.

NumDealsPurchases: Número de compras feitas com desconto

NumStorePurchases: Número de compras feitas diretamente nas lojas.

NumWebVisitsMonth: Número de visitas ao site da empresa no último mês.






**WebPurchases: Número de compras feitas pelo site da empresa.**

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ETAPA 1:

**Preparação dos Dados**

**Exploração e Limpeza:** Analisar e limpar os dados para garantir que estejam prontos para a modelagem.

**Análise:** Construa uma storytelling com gráficos, analisando e retirando insights das informações.

In [2]:
base = pd.read_csv('marketing_campaign.csv', delimiter=';')

In [4]:
base

,Year_Birth,Education,Marital_Status,Income,Kidhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumStorePurchases,NumWebVisitsMonth,Complain,WebPurchases
0,1957,Graduation,Single,58138.0,0,58,635,88,546,172,88,88,4,7,0,1
1,1954,Graduation,Single,46344.0,1,38,11,1,6,2,1,6,2,5,0,0
2,1965,Graduation,Together,71613.0,0,26,426,49,127,111,21,42,10,4,0,1
3,1984,Graduation,Together,26646.0,1,26,11,4,20,10,3,5,4,6,0,0
4,1981,PhD,Married,58293.0,1,94,173,43,118,46,27,15,6,5,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,1967,Graduation,Married,61223.0,0,46,709,43,182,42,118,247,4,5,0,1
2236,1946,PhD,Together,64014.0,2,56,406,0,30,0,0,8,5,7,0,1
2237,1981,Graduation,Divorced,56981.0,0,91,908,48,217,32,12,24,13,6,0,0
2238,1956,Master,Together,69245.0,0,8,428,30,214,80,30,61,10,3,0,1
2239,1954,PhD,Married,52869.0,1,40,84,3,61,2,1,21,4,7,0,0

In [5]:
base.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year_Birth         2240 non-null   int64
 1   Education          2240 non-null   str
 2   Marital_Status     2240 non-null   str
 3   Income             2216 non-null   float64
 4   Kidhome            2240 non-null   int64
 5   Recency            2240 non-null   int64
 6   MntWines           2240 non-null   int64
 7   MntFruits          2240 non-null   int64
 8   MntMeatProducts    2240 non-null   int64
 9   MntFishProducts    2240 non-null   int64
 10  MntSweetProducts   2240 non-null   int64
 11  MntGoldProds       2240 non-null   int64
 12  NumStorePurchases  2240 non-null   int64
 13  NumWebVisitsMonth  2240 non-null   int64
 14  Complain           2240 non-null   int64
 15  WebPurchases       2240 non-null   int64
dtypes: float64(1), int64(13), str(2)
memory usage: 280.1 KB

In [6]:
# 24 dados "nulos" ou faltantes
base['Income'].isna().sum()

np.int64(24)

In [7]:
# ferifiquei as linas que estavam faltando no Income
base[base['Income'].isna()]

,Year_Birth,Education,Marital_Status,Income,Kidhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumStorePurchases,NumWebVisitsMonth,Complain,WebPurchases
10,1983,Graduation,Married,NaN,1,11,5,5,6,0,2,1,2,7,0,0
27,1986,Graduation,Single,NaN,1,19,5,1,3,3,263,362,0,1,0,1
43,1959,PhD,Single,NaN,0,80,81,11,50,3,2,39,4,2,0,0
48,1951,Graduation,Single,NaN,2,96,48,5,48,6,10,7,4,6,0,0
58,1982,Graduation,Single,NaN,1,57,11,3,22,2,2,6,3,6,0,0
71,1973,2n Cycle,Married,NaN,1,25,25,3,43,17,4,17,3,8,0,0
90,1957,PhD,Married,NaN,2,4,230,42,192,49,37,53,8,9,0,1
91,1957,Graduation,Single,NaN,1,45,7,0,8,2,0,1,2,7,0,0
92,1973,Master,Together,NaN,0,87,445,37,359,98,28,18,8,1,0,0
128,1961,PhD,Married,NaN,0,23,352,0,27,10,0,15,7,6,0,1
133,1963,Graduation,Married,NaN,0,96,231,65,196,38,71,124,7,4,0,1
312,1989,Graduation,Married,NaN,0,69,861,138,461,60,30,61,12,3,0,1
319,1970,Graduation,Single,NaN,1,67,738,20,172,52,50,20,10,7,0,0
1379,1970,Master,Together,NaN,0,39,187,5,65,26,20,14,6,5,0,1
1382,1958,Graduation,Together,NaN,1,87,19,4,12,2,2,6,3,5,0,0
1383,1964,2n Cycle,Single,NaN,1,49,5,1,9,2,0,4,2,7,0,0
1386,1972,PhD,Together,NaN,1,17,25,1,13,0,0,3,3,7,0,0
2059,1969,Master,Together,NaN,1,52,375,42,48,94,66,96,4,3,0,1
2061,1981,PhD,Single,NaN,1,82,23,0,15,0,2,7,3,6,0,0
2078,1971,Graduation,Married,NaN,1,82,71,1,16,0,0,9,3,8,0,0
2079,1954,Master,Together,NaN,0,83,161,0,22,0,0,24,4,6,0,1
2081,1955,Graduation,Single,NaN,0,95,264,0,21,12,6,147,5,7,0,1
2084,1943,Master,Widow,NaN,0,75,532,126,490,164,126,126,11,1,0,1
2228,1978,2n Cycle,Together,NaN,0,53,32,2,1607,12,4,22,1,0,0,0

In [8]:
# gostaria de inspecionar quais o valores que estao sendo impressos nessas colunas
# analisar se nao tem nenhum dado absurdo
for col in ['Education', 'Marital_Status', 'Complain', 'WebPurchases']:
    print('\n', col)
    print(base[col].value_counts())

 Education
Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

 Marital_Status
Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

 Complain
Complain
0    2219
1      21
Name: count, dtype: int64

 WebPurchases
WebPurchases
1    1128
0    1112
Name: count, dtype: int64

In [9]:
base.describe()

,Year_Birth,Income,Kidhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumStorePurchases,NumWebVisitsMonth,Complain,WebPurchases
count,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000
mean,1968.805804,52247.251354,0.444196,49.109375,303.935714,26.302232,166.950000,37.525446,27.062946,44.021875,5.790179,5.316518,0.009375,0.503571
std,11.984069,25173.076661,0.538398,28.962453,336.597393,39.773434,225.715373,54.628979,41.280498,52.167439,3.250958,2.426645,0.096391,0.500099
min,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1959.000000,35303.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,1.000000,9.000000,3.000000,3.000000,0.000000,0.000000
50%,1970.000000,51381.500000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,8.000000,24.000000,5.000000,6.000000,0.000000,1.000000
75%,1977.000000,68522.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,33.000000,56.000000,8.000000,7.000000,0.000000,1.000000
max,1996.000000,666666.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,263.000000,362.000000,13.000000,20.000000,1.000000,1.000000

In [15]:
# visao geral do database
print('Linhas, colunas:', base.shape)
print('\nDuplicados:', base.duplicated().sum())
print('\nValores faltantes:')
print(base.isna().sum())

Linhas, colunas: (2240, 16)

Duplicados: 201

Valores faltantes:
Year_Birth            0
Education             0
Marital_Status        0
Income               24
Kidhome               0
Recency               0
MntWines              0
MntFruits             0
MntMeatProducts       0
MntFishProducts       0
MntSweetProducts      0
MntGoldProds          0
NumStorePurchases     0
NumWebVisitsMonth     0
Complain              0
WebPurchases          0
dtype: int64

In [20]:
# confirmacao de duplicacao
print('Excedentes:', base.duplicated().sum())
print('Total em grupos duplicados:', base[base.duplicated(keep=False)].shape[0])

Excedentes: 201
Total em grupos duplicados: 394

Foram identificados 201 linhas duplicadas. Entretaanto como a passe nao possui ID unico, nao é possivel garantir qeu estas linhas sejam erros de cadastro.
Estas repetições podem representar clientes distintos, entao optei por manter essa parte de base e não exclui-la. pois representaria quase 10% de toda a base perdida neste caso.

In [21]:
# tratando os dados faltantes de Income - NaN. Neste caso prerimos imputar a mediana nestes casos
# Assim não é necessário excluir estes dados
base['Income'] = base['Income'].fillna(base['Income'].median())

In [22]:
# proxima etape é verificacao de outliers e visualizaçao grafica
colunas_numericas = [
    'Year_Birth', 'Income', 'Kidhome', 'Recency', 'MntWines',
    'MntFruits', 'MntMeatProducts', 'MntFishProducts',
    'MntSweetProducts', 'MntGoldProds',
    'NumStorePurchases', 'NumWebVisitsMonth'
]

for col in colunas_numericas:
    q1 = base[col].quantile(0.25)
    q3 = base[col].quantile(0.75)
    iqr = q3 - q1
    limite_inferior = q1 - 1.5 * iqr
    limite_superior = q3 + 1.5 * iqr
    
    qtd = base[(base[col] < limite_inferior) | (base[col] > limite_superior)].shape[0]

    print(f'\n{col}')
    print(f'Q1: {q1}')
    print(f'Q3: {q3}')
    print(f'IQR: {iqr}')
    print(f'Limite inferior: {limite_inferior}')
    print(f'Limite superior: {limite_superior}')
    print(f'Quantidade de outliers: {qtd}')

Year_Birth
Q1: 1959.0
Q3: 1977.0
IQR: 18.0
Limite inferior: 1932.0
Limite superior: 2004.0
Quantidade de outliers: 3

Income
Q1: 35538.75
Q3: 68289.75
IQR: 32751.0
Limite inferior: -13587.75
Limite superior: 117416.25
Quantidade de outliers: 8

Kidhome
Q1: 0.0
Q3: 1.0
IQR: 1.0
Limite inferior: -1.5
Limite superior: 2.5
Quantidade de outliers: 0

Recency
Q1: 24.0
Q3: 74.0
IQR: 50.0
Limite inferior: -51.0
Limite superior: 149.0
Quantidade de outliers: 0

MntWines
Q1: 23.75
Q3: 504.25
IQR: 480.5
Limite inferior: -697.0
Limite superior: 1225.0
Quantidade de outliers: 35

MntFruits
Q1: 1.0
Q3: 33.0
IQR: 32.0
Limite inferior: -47.0
Limite superior: 81.0
Quantidade de outliers: 227

MntMeatProducts
Q1: 16.0
Q3: 232.0
IQR: 216.0
Limite inferior: -308.0
Limite superior: 556.0
Quantidade de outliers: 175

MntFishProducts
Q1: 3.0
Q3: 50.0
IQR: 47.0
Limite inferior: -67.5
Limite superior: 120.5
Quantidade de outliers: 223

MntSweetProducts
Q1: 1.0
Q3: 33.0
IQR: 32.0
Limite inferior: -47.0
Limite superior: 81.0
Quantidade de outliers: 248

MntGoldProds
Q1: 9.0
Q3: 56.0
IQR: 47.0
Limite inferior: -61.5
Limite superior: 126.5
Quantidade de outliers: 207

NumStorePurchases
Q1: 3.0
Q3: 8.0
IQR: 5.0
Limite inferior: -4.5
Limite superior: 15.5
Quantidade de outliers: 0

NumWebVisitsMonth
Q1: 3.0
Q3: 7.0
IQR: 4.0
Limite inferior: -3.0
Limite superior: 13.0
Quantidade de outliers: 8

# ETAPA 2:
**Pré-processamento**

**Análise Correlação:** Verifique a correlação entre as váriaveis e análise se há espaço para retirar váriaveis que não te parecem importantes.

**Codificação de Variáveis Categóricas:** Transformar variáveis categóricas em um formato que os modelos de machine learning possam interpretar.


**Separe a base em Y, X e Treino e teste:**: Faça a separação da base.

**Realize a padronização dos dados**: Padronize os dados para garantir eficiência no modelo e eficácia.

In [ ]:
# seu código aqui

# ETAPA 3:

**Modelagem**

Escolha ao menos 2 técnicas de machine learning e rode 2 modelos, afim de identificar qual tem o melhor resultado para essa base. Lembrando que estamos lidando com uma classificação binária.

In [ ]:
# seu código aqui

# ETAPA 4:

**Avaliação**

Avalie os resultados encontrados nos dois modelos e identifique qual te pareceu realizar melhor as previsões.

Utilize além das métricas padrões a matriz de confusão.

In [ ]:
# seu código aqui